### ISSUE TITLE
Missing / messed up PDOs in binary format

### ISSUE THREAD

**Issue by uecasm** [synapticon/siitool#16]
As an experiment, I started with the well-known ESI for the Beckhoff EL2002 (first device in the [Beckhoff EL2xxx.xml ESI file](https://download.beckhoff.com/download/configuration-files/io/ethercat/xml-device-description/Beckhoff_EtherCAT_XML.zip)).

```
$ ./siitool -p 'Beckhoff EL2xxx.xml'
```
This prints a bunch of info, notably including reasonable RxPDO definitions (apart from "undefined" heading, perhaps):
```
Print Categorie: RX PDO (0x33)
  Size: 16 Bytes
  undefined:
    PDO Index: .................. 0x1600
    Entries: .................... 1
    SyncM: ...................... 0
    Synchronization: ............ 0x00
    Name Index: ................. 3
    Flags for future use: ....... 0x0000

      Entry 0:
      Entry Index: .............. 0x3001
      Subindex: ................. 0x01
      String Index: ............. 4 (Output)
      Data Type: ................ 0x01 (Index in CoE Object Dictionary)
      Bitlength: ................ 1
      Flags (for future use): ... 0x0000

Print Categorie: RX PDO (0x33)
  Size: 16 Bytes
  undefined:
    PDO Index: .................. 0x1601
    Entries: .................... 1
    SyncM: ...................... 0
    Synchronization: ............ 0x00
    Name Index: ................. 5
    Flags for future use: ....... 0x0000

      Entry 0:
      Entry Index: .............. 0x3001
      Subindex: ................. 0x02
      String Index: ............. 6 (Output)
      Data Type: ................ 0x01 (Index in CoE Object Dictionary)
      Bitlength: ................ 1
      Flags (for future use): ... 0x0000
```

Converting that to binary with your tool and then trying to interpret it fails, though:
```
$ ./siitool -o el2002.bin 'Beckhoff EL2xxx.xml'
= el2002.bin generated
$ ./siitool -p el2002.bin
```
The resulting output stops after printing the SyncManager category and does not print any PDOs at all.  (I did not check whether the bin file was correct or not.)

I then tried using Beckhoff's own EEPROM tool (from the SSC) to produce a bin file and decode that:
```
$ ./siitool -p 'Beckhoff EL2002.bin'
```
The output for this does include the RxPDO category but all squished together (it's reporting the second PDO as if it were an entry of the first):
```
Print Categorie: RX PDO (0x33)
  Size: 32 Bytes
  RxPDO:
    PDO Index: .................. 0x1600
    Entries: .................... 1
    SyncM: ...................... 0
    Synchronization: ............ 0x00
    Name Index: ................. 3
    Flags for future use: ....... 0x0000

      Entry 0:
      Entry Index: .............. 0x3001
      Subindex: ................. 0x01
      String Index: ............. 4 (Output)
      Data Type: ................ 0x01 (Index in CoE Object Dictionary)
      Bitlength: ................ 1
      Flags (for future use): ... 0x0000

      Entry 1:
      Entry Index: .............. 0x1601
      Subindex: ................. 0x01
      String Index: ............. 0 (not set)
      Data Type: ................ 0x00 (Index in CoE Object Dictionary)
      Bitlength: ................ 5
      Flags (for future use): ... 0x0000

      Entry 2:
      Entry Index: .............. 0x3001
      Subindex: ................. 0x02
      String Index: ............. 4 (Output)
      Data Type: ................ 0x01 (Index in CoE Object Dictionary)
      Bitlength: ................ 1
      Flags (for future use): ... 0x0000
```

(On an unrelated note, the `Print Categorie: DC CLOCK (0x3c)` seems weird too, and the PDO flags are not "for future use".  I think you read the wrong section of ETG1000 and need to look at ETG2010 instead.)

**Comment by fjes** [comment]
Hi and thank you for reporting this issue. The current version of this tool no longer creates the PDO mapping by default. To have the PDO mapping in the resulted SII binary file please add the command line option `-m` (for mapping).

I will take a look where this `undefined` in the print out of the XML comes from, thanks for pointing that out.

The last print out of the PDO mapping of the SII binary is a bug. I will try to fix for the next release.

Thank you and sorry for the belated response.

**Comment by fjes** [comment]
v2.2 seem to resolve the PDO printing issue.

PDO flags and DC section support is planned for one of the next releases. Since the PDO printing was the issue here I'll close this issue. Thanks again for reporting.
