### ISSUE TITLE
DefaultSize in MBoxOut and MBoxIn seems to be handled incorrectly

### ISSUE THREAD

**Issue by peersch** [synapticon/siitool#17]
For the standard mailbox configuration the data type of the DefaultSize for MBoxOut and MBoxIn is, according to the "EtherCAT Slave Information Specification", a HexDecValue. IMHO, both entries should be parsed using the scan_hex_dec function, not using atoi, as the latter one always returns 0 as it does not understand '#x'

**Comment by fjes** [comment]
Thanks @berkayarslan17
