### ISSUE TITLE
DataType REAL is written an UINT32

### ISSUE THREAD

**Issue by TadyTheFish** [synapticon/siitool#19]
Hello
First of all, VERY nice tool.
I am a total beginner in EtherCAT and I'm learning as I go.
I'm making a custom slave device with LAN9252. I made the XML file with EasyConfigurator . I used your tool to convert it to bin. 
My file is simple one REAL (float) input and output. But it does not work. 
I used EtherLabs ethercat stack to upload the bin and then I checked the uploaded data with "ethercat xml" to print it back.
The printed content is OK except for the DataType. It should be "REAL" but it's "UINT32". 
Is there a problem with your converter or am I doing something stupid
Thank you

**Comment by fjes** [comment]
Hi @TadyTheFish thank you for using this tool. Without knowing the ESI and SII binary it is hard to tell. Can you please attach these two files and the output of `ethercat xml` please?

**Comment by TadyTheFish** [comment]
Thank you
Here they are 
[Tady.tar.gz](https://github.com/synapticon/siitool/files/11562248/Tady.tar.gz)

And the ethercat xml output...
`<?xml version="1.0" ?>
<EtherCATInfoList>
  <EtherCATInfo>
    
    <Vendor>
      <Id>5596740</Id>
    </Vendor>
    <Descriptions>
      <Devices>
        <Device>
          <Type ProductCode="#x00000005" RevisionNo="#x00000001"></Type>
          <Name><![CDATA[TadySlave]]></Name>
          <Sm Enable="1" StartAddress="#x1000" ControlByte="#x64" DefaultSize="0" />
          <Sm Enable="1" StartAddress="#x1200" ControlByte="#x20" DefaultSize="0" />
          <RxPdo Sm="0" Fixed="1" Mandatory="1">
            <Index>#x1600</Index>
            <Name>Outputs</Name>
            <Entry>
              <Index>#x0005</Index>
              <SubIndex>1</SubIndex>
              <BitLen>32</BitLen>
              <Name>outputFloat</Name>
              <DataType>UINT32</DataType>
            </Entry>
          </RxPdo>
          <TxPdo Sm="1" Fixed="1" Mandatory="1">
            <Index>#x1a00</Index>
            <Name>Inputs</Name>
            <Entry>
              <Index>#x0006</Index>
              <SubIndex>1</SubIndex>
              <BitLen>32</BitLen>
              <Name>inputFloat</Name>
              <DataType>UINT32</DataType>
            </Entry>
          </TxPdo>
        </Device>
      </Devices>
    </Descriptions>
  </EtherCATInfo>
  <EtherCATInfo>
    
    <Vendor>
      <Id>5596740</Id>
    </Vendor>
    <Descriptions>
      <Devices>
        <Device>
          <Type ProductCode="#x00000005" RevisionNo="#x00000001"></Type>
          <Name><![CDATA[TadySlave]]></Name>
          <Sm Enable="1" StartAddress="#x1000" ControlByte="#x64" DefaultSize="0" />
          <Sm Enable="1" StartAddress="#x1200" ControlByte="#x20" DefaultSize="0" />
          <RxPdo Sm="0" Fixed="1" Mandatory="1">
            <Index>#x1600</Index>
            <Name>Outputs</Name>
            <Entry>
              <Index>#x0005</Index>
              <SubIndex>1</SubIndex>
              <BitLen>32</BitLen>
              <Name>outputFloat</Name>
              <DataType>UINT32</DataType>
            </Entry>
          </RxPdo>
          <TxPdo Sm="1" Fixed="1" Mandatory="1">
            <Index>#x1a00</Index>
            <Name>Inputs</Name>
            <Entry>
              <Index>#x0006</Index>
              <SubIndex>1</SubIndex>
              <BitLen>32</BitLen>
              <Name>inputFloat</Name>
              <DataType>UINT32</DataType>
            </Entry>
          </TxPdo>
        </Device>
      </Devices>
    </Descriptions>
  </EtherCATInfo>
</EtherCATInfoList>`
And if you need the ethercat cstruct output
`/* Master 0, Slave 0
 * Vendor ID:       0x00556644
 * Product code:    0x00000005
 * Revision number: 0x00000001
 */

ec_pdo_entry_info_t slave_0_pdo_entries[] = {
    {0x0005, 0x01, 32}, /* outputFloat */
    {0x0006, 0x01, 32}, /* inputFloat */
};

ec_pdo_info_t slave_0_pdos[] = {
    {0x1600, 1, slave_0_pdo_entries + 0}, /* Outputs */
    {0x1a00, 1, slave_0_pdo_entries + 1}, /* Inputs */
};

ec_sync_info_t slave_0_syncs[] = {
    {0, EC_DIR_OUTPUT, 1, slave_0_pdos + 0, EC_WD_ENABLE},
    {1, EC_DIR_INPUT, 1, slave_0_pdos + 1, EC_WD_DISABLE},
    {0xff}
};
`

**Comment by fjes** [comment]
Hi thank you for the report. This is a bug in the PDO parsing from the ESI file. I give you a notification when it is fixed.

**Comment by TadyTheFish** [comment]
I will test in the evening. Yes I forgot to mention... I changed REAL to REAL32 my self when I tought that maybe that would work... In my original XML it is REAL

**Comment by TadyTheFish** [comment]
I don't get it "ethercat xml" still reports the slave config as UINT32.
I use TwinCAT3 for testing and it works. But when I use LinuxCNC it does not work.
When writing and reading the data gets wierd

**Comment by TadyTheFish** [comment]
Thank you for your fix but this is clearly an LCEC issue.
