### ISSUE TITLE
Documentation not available

### ISSUE THREAD

**Issue by STA-STA** [synapticon/siitool#22]
Link to the Documentation of the Tool is broken and the Website doesn't seem to offer it anymore.

**Comment by fjes** [comment]
Hi STA-STA, thank you for the report. Which link do you refer to and where is it to find? In the man page? In the help output?

**Comment by dongly** [comment]
https://github.com/synapticon/siitool/blob/8d446c2634b25d0956a81a9bfbf931012b55db94/README.rst?plain=1#L12

**Comment by fjes** [comment]
Oh yes, thank you for reporting.
