### ISSUE TITLE
Segmentation fault:11

### ISSUE THREAD

**Issue by kaizen-nagoya** [synapticon/siitool#9]
$/usr/local/bin/siitool -p  bigfile.xml 
Segmentation fault: 11

I tried some big files size  From 1.1Mb to 15M.
Some makers provide such big EtherCat xml files.

**Comment by gostohov** [comment]
i ve got with too...Did u soldev it ?

**Comment by sparksh** [comment]
I just submitted a change. If you're in a hurry, see: [Branch to fix segfault](https://github.com/sparksh/siitool.git)

**Comment by fjes** [comment]
> I like all of your suggestions, but using mmap or even getting the file size is very difficult because the program gets the file from stdin when no filename is provided on the command line.
>
> What do you think about changing siitool so the filename must be specified on the command line? (No stdin) I realize that might break existing scripts that use siitool, but I don't see a nice alternative if you want to get rid of MAX_BUFFER_SIZE.
>
> I added free(eeprom) as you suggested. It's on my branch fix-large-esi-segfault.

In the current implementation the you can specify a filename at the command line. Like this:

```$ siitool -o some.sii some.xml```

I liked the idea of supporting pipes, but you are right, due to the memory assignment necessary to parse the necessary XML fields the pipline support may have to disappear.

**Comment by fjes** [comment]
Thanks to @sparksh the problem now only happen for files larger than 10MB. I think realloc could be a good candidate for arbitrary sized ESI files. I only hope the libxml2 doesn't have a limitation in place somewhere.

**Comment by fjes** [comment]
With commit 655e7c292a7abaa5bbca0bad3c76d434c6e551fc the overflow bug should be solved with arbitrary sized input files (ESI) independent if they passed via pipe or read as input file.

Sorry for the long delay.
